/**
 * Tunnel wire protocol (v1 — single multiplexed WS).
 *
 * A single WebSocket lives between each iClaw process and the relay.
 * Logical tunnels (each presented to the public as `<sub>.<baseDomain>`)
 * are multiplexed over that single connection. Every frame carries a
 * `tunnelId` so the receiver knows which logical tunnel the frame
 * belongs to. The `tunnelId` is generated by iClaw and is stable across
 * relay reconnects.
 *
 * The relay assigns a subdomain in response to `register-tunnel` and
 * tells iClaw about it via `tunnel-registered`. The same `tunnelId`
 * re-registered within the reconnect grace window keeps the original
 * subdomain; after the window, or on first register, a new subdomain
 * is minted.
 *
 * All bodies are base64-encoded; v1 is non-streaming.
 */

/* ---- control frames ─────────────────────────────────────────────── */

/** iClaw → relay: ask the relay to allocate a subdomain for `tunnelId`. */
export interface RegisterTunnelFrame {
  t: 'register-tunnel';
  tunnelId: string;
  label?: string | null;
  /** SHA-256(access token) base64url — relay stores hash only, never plaintext. */
  tokenHash: string;
  /**
   * Tunnel ownership secret (base64url, ≥128-bit). Proves the registering
   * client is the same iClaw that originally created this tunnelId, so a
   * stranger who merely guesses/observes the (low-entropy) tunnelId cannot
   * hijack the subdomain via a reconnect "restore" or rotate its access token.
   *
   * The relay stores only SHA-256(ownerProof). Optional for backward compat:
   * tunnels first registered without it carry a null owner hash and keep the
   * legacy (unauthenticated) restore behaviour.
   */
  ownerProof?: string;
}

/** relay → iClaw: subdomain assigned. Sent in response to register-tunnel. */
export interface TunnelRegisteredFrame {
  t: 'tunnel-registered';
  tunnelId: string;
  subdomain: string;
  baseDomain: string;
  publicUrl: string;
}

/** relay → iClaw: registration refused (rate limit, conflict, …). */
export interface TunnelRejectedFrame {
  t: 'tunnel-rejected';
  tunnelId: string;
  reason: string;
  retryAfterSec?: number;
}

/** iClaw → relay: stop forwarding to this tunnel; free its subdomain. */
export interface UnregisterTunnelFrame {
  t: 'unregister-tunnel';
  tunnelId: string;
}

/* ---- request / response frames ──────────────────────────────────── */

export interface ReqFrame {
  t: 'req';
  /** Which logical tunnel this request belongs to. */
  tunnelId: string;
  /** Per-request correlation id (echoed back in the matching res/err). */
  id: string;
  method: string;
  path: string;
  headers: Record<string, string>;
  body: string;
}

export interface ResFrame {
  t: 'res';
  tunnelId: string;
  id: string;
  status: number;
  headers: Record<string, string>;
  body: string;
}

export interface ErrFrame {
  t: 'err';
  tunnelId: string;
  id?: string;
  message: string;
}

/* ---- WS-stream frames (subscribed websockets through the tunnel) ── */

export interface WsOpenFrame {
  t: 'ws-open';
  tunnelId: string;
  id: string;
  path: string;
  headers: Record<string, string>;
}

export interface WsDataFrame {
  t: 'ws-data';
  tunnelId: string;
  id: string;
  binary: boolean;
  data: string;
}

export interface WsCloseFrame {
  t: 'ws-close';
  tunnelId: string;
  id: string;
  code?: number;
  reason?: string;
}

/* ---- keep-alive ─────────────────────────────────────────────────── */

export interface PingFrame { t: 'ping' }
export interface PongFrame { t: 'pong' }

export type Frame =
  | RegisterTunnelFrame
  | TunnelRegisteredFrame
  | TunnelRejectedFrame
  | UnregisterTunnelFrame
  | ReqFrame
  | ResFrame
  | ErrFrame
  | WsOpenFrame
  | WsDataFrame
  | WsCloseFrame
  | PingFrame
  | PongFrame;

/* ---- header sanitisation ───────────────────────────────────────── */

export const HOP_BY_HOP_HEADERS = new Set([
  'connection',
  'keep-alive',
  'proxy-authenticate',
  'proxy-authorization',
  'te',
  'trailers',
  'transfer-encoding',
  'upgrade',
  'host',
  'content-length',
]);

/**
 * Internal-only header prefix used between relay and local iClaw. We
 * strip incoming public headers matching it before forwarding through
 * the tunnel; otherwise a public client could forge e.g.
 * `x-iclaw-tunneled` or `x-iclaw-tunnel-id` and bypass internal gates.
 */
export const INTERNAL_HEADER_PREFIX = 'x-iclaw-';

export function stripHopByHopHeaders(
  headers: Record<string, string | string[] | undefined>,
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(headers)) {
    if (v === undefined) continue;
    const lower = k.toLowerCase();
    if (HOP_BY_HOP_HEADERS.has(lower)) continue;
    if (lower.startsWith(INTERNAL_HEADER_PREFIX)) continue;
    out[lower] = Array.isArray(v) ? v.join(', ') : v;
  }
  return out;
}

export function parseFrame(raw: string): Frame | null {
  try {
    const obj = JSON.parse(raw) as Frame;
    if (typeof obj !== 'object' || obj === null || typeof (obj as { t?: unknown }).t !== 'string') {
      return null;
    }
    return obj;
  } catch {
    return null;
  }
}
